---
title: "Analysis"
author: "Charlie Bayne"
date: "`r Sys.Date()`"
output:
  html_document:
        theme: cosmo
        toc: true
        toc_depth: 6
        toc_float:
            collapsed: true
            smooth_scroll: true
        code_folding: hide
        highlight: tango
        df_print: paged
---

```{r setup, include=FALSE}
library(tidyverse)
ggplot2::theme_set(ggprism::theme_prism(palette = "viridis"))
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

# Processing 


```{r}
library(mspms)
prepared_data = prepare_peaks("../data/cathepsins/protein-peptides-lfq.csv",
                              "../data/cathepsins/protein-peptides-id.csv")


design_matrix = readr::read_csv("../data/cathepsins/design_matrix.csv")

mspms_data = mspms(prepared_data,
                   design_matrix)


no_cleave_preprocessed = prepared_data %>% 
  filter(!grepl(".*_.*",Peptide))



no_cleave_processed = mspms_data %>% 
  filter(!grepl(".*_.*",Peptide))


```



We are losing the full length peptides at some point of the mspms pipeline. We will investigate this further. 


```{r}

outdir = getwd()

# Normalyzing data
  normalyzed_data <- mspms::normalyze(prepared_data, design_matrix, outdir)
  
  no_cleave_norm = normalyzed_data %>% 
  filter(!grepl(".*_.*",Peptide))
  
  
  # handle outliers, impute
  outliers <- mspms::handle_outliers(normalyzed_data, design_matrix)
  
  no_cleave_out = outliers %>% 
  filter(!grepl(".*_.*",Peptide))
  
  imputed <- mspms::impute(outliers)
  
  no_cleave_impute = imputed %>% 
  filter(!grepl(".*_.*",Peptide))
  
  # Join with the library
  joined_with_library <- mspms::join_with_library(imputed)
  
  no_cleave_join = joined_with_library %>% 
  filter(!grepl(".*_.*",Peptide))
         
  # Add cleavage information
  cleavage_added_data <- mspms::add_cleavages(joined_with_library,
    n_residues = 4
  )
  
   no_cleave_cleave = cleavage_added_data %>% 
  filter(!grepl(".*_.*",Peptide))

  # Prepare for stats
  prepared_for_stats <- mspms::prepare_for_stats(
    cleavage_added_data,
    design_matrix
  )
  
     no_cleave_stats = prepared_for_stats %>% 
  filter(!grepl(".*_.*",Peptide))

  # Polish for downstream analysis (gets rid of cases with  n and c cleavages)
  polished_data <- mspms::polish(prepared_for_stats)
  
  no_cleave_polish = polished_data %>% 
  filter(!grepl(".*_.*",Peptide))

```


```{r}

cleavage_added_data = prepared_for_stats


# fixing thefunction
  out <- cleavage_added_data %>%
    # consolidating cleavage sequence
    dplyr::mutate(cleavage_seq = dplyr::case_when(
      !is.na(nterm) & is.na(cterm) ~ nterm,
      !is.na(cterm) & is.na(nterm) ~ cterm,
      TRUE ~ NA
    ), .after = "cterm_cleavage_pos") %>%
    # Removing peptides with double cleavages
    dplyr::filter(!(!is.na(.data$cterm) & !is.na(.data$nterm))) %>%
    dplyr::mutate(cleavage_pos = dplyr::case_when(
      is.na(cterm_cleavage_pos) ~ nterm_cleavage_pos,
      TRUE ~ cterm_cleavage_pos
    ), .after = "cleavage_seq") %>%
    # Adding information about whether detected peptide was cleaved or not
    dplyr::mutate(cleavage_type = dplyr::case_when(
      grepl(".*_.*", Peptide) ~ "cleaved",
      TRUE ~ "uncleaved"
    ), .after = "cleavage_pos") %>%
    tibble::as_tibble()
  
    
    
  plot_heatmap(out)
  
  
  plot_heatmap(no_cleave_out)
  
```

```{r}

mspms_data = out 

peptide_libary = mspms::peptide_library

library_peptides = prepared_data %>%
  pivot_longer(4:length(.),names_to ="sample") %>% 
  filter(!grepl(".*_.*",Peptide)) %>%
  filter(!is.na(value)) %>% 
  group_by(sample) %>% 
  summarise(n = dplyr::n_distinct(Peptide)) %>% 
  inner_join(design_matrix,by = "sample")


# plotting over time. 
p1 = ggplot(library_peptides,aes(x = time, y = n)) + 
  geom_point() + 
  geom_smooth() + 
  geom_hline(yintercept = 228,linetype = "dashed") +
  geom_hline(yintercept = 200,linetype = "dashed") +
  facet_wrap(~condition,scales ="free")

p1



library_peptides_including_cleavages = prepared_data %>%
  pivot_longer(4:length(.),names_to = "sample") %>% 
  filter(!is.na(value)) %>% 
  group_by(sample) %>% 
  summarise(n = dplyr::n_distinct(`Protein Accession`)) %>% 
  inner_join(design_matrix,by = "sample")


# plotting over time

p1 = ggplot(library_peptides_including_cleavages,aes(x = time, y = n)) + 
  geom_point() + 
  geom_smooth() + 
  geom_hline(yintercept = 228,linetype = "dashed") +
  geom_hline(yintercept = 200,linetype = "dashed") +
  facet_wrap(~condition,scales ="free")

p1

`%!in%` = Negate(`%in%`) 


proteins_not_detected = prepared_data[4:length(prepared_data)]


find_not_in_library = function()


  pivot_longer(4:length(.),names_to = "sample") %>% 
  filter(!is.na(value)) %>% 
  group_by(sample) %>% 
  summarise(n = dplyr::n_distinct(`Protein Accession`)) %>% 
  inner_join(design_matrix,by = "sample")

not_detected = peptide_libary$library_reference_id[peptide_libary$library_reference_id %!in% prepared_data$`Protein Accession`]

not_detected 
```





